#!/bin/bash

if [ $# -lt 1 ]; then
    echo '$0 <app>'
    exit 1
fi

APP=$1
PROFILE_DIR=${2:-profiling}

SLEEP=${SLEEP:-5}
PERF=${PERF:-perf}
FREQ=${FREQ:-99}

CALLGRAPH=${CALLGRAPH:-fp}
STACKSIZE=${STACKSIZE:-128}

if [ ! -x $APP ]; then
    echo '$APP not executable'
    exit 2
fi

echo "=== $0:  PERF=$PERF, SLEEP=$SLEEP, CALLGRAPH=$CALLGRAPH"

rm -f core
ulimit -c unlimited
mkdir -p $PROFILE_DIR
rm -rf $PROFILE_DIR/perf.*

$APP >/dev/null &
PID=$!

sleep 1
ps -p $PID
if [ $? -ne 0 ]; then
   echo $APP did not start
   exit 2
fi

if [ "$CALLGRAPH" = "dwarf" ]; then
    $PERF record --no-buildid --no-buildid-cache -g --call-graph $CALLGRAPH,$STACKSIZE -F $FREQ -p $PID -o $PROFILE_DIR/perf.data sleep $SLEEP
else
    $PERF record --no-buildid --no-buildid-cache -g --call-graph $CALLGRAPH -F $FREQ -p $PID -o $PROFILE_DIR/perf.data sleep $SLEEP
fi
#$PERF record -v -g --call-graph $CALLGRAPH -F $FREQ -p $PID -o $PROFILE_DIR/perf.data sleep $SLEEP
#$PERF archive $PROFILE_DIR/perf.data
cat /proc/kallsyms > $PROFILE_DIR/kallsyms

if [ -e $PROFILE_DIR/perf.data ]; then
    $PERF script --header -i $PROFILE_DIR/perf.data -I -F comm,pid,tid,time,event,ip,sym,dso,period > $PROFILE_DIR/perf.out
else
    echo "$PROFILE_DIR/perf.data is missing!!!"
fi

kill $PID

if [ -e core ]; then
    exit 1
else
    exit 0
fi
